apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  resources: # 为 Tasks 提供输入和输出资源声明
    - name: git-res
      type: git
    - name: ucloud-image-go
      type: image
  params:
    - name: image-tag
      type: string      
  tasks: # 添加task到流水线中
    - name: get-build-id
      taskRef:
        name: generate-build-id # 引入generate-build-id task
      params:
        - name: base-version
          value: $(params.image-tag)  
    # 运行应用测试
    - name: test
      taskRef:
        name: test
      resources:
        inputs:
          - name: repo # Task 输入名称
            resource: git-res # Pipeline 资源名称
    # 构建并推送 Docker 镜像
    - name: build-and-push-test
      taskRef:
        name: build-and-push-test
      runAfter:
        - test # 测试任务执行之后
        - get-build-id
      resources:
        inputs:
          - name: repo # 指定输入的git仓库资源
            resource: git-res
        outputs: # 指定输出的镜像资源
          - name: linuxea
            resource: ucloud-image-go
      params:
        - name: imageTag
          value: "$(tasks.get-build-id.results.build-id)"