# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mvn-repo-pvc
# spec:
#   resources:
#     requests:
#       storage: 5Gi
#   volumeMode: Filesystem
#   storageClassName: nfs-client # 使用 StorageClass 自动生成 PV
#   accessModes:
#     - ReadWriteOnce
# 或者手动生成
# mkdir -p /data/nfs-share/tekton-workspaces-build
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-workspaces
  namespace: default
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.100.49
    path: /data/nfs-share/tekton-workspaces-build
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspaces
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi