apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argo-sync-app
spec:
  volumes:
    - name: argocd-secret
      secret:
        secretName: $(inputs.params.argocd_secret)
  params:
    - name: argocd_url
      description: "The URL of the ArgoCD server"
    - name: argocd_secret
      description: "The secret containing the username and password for the tekton task to connect to argo"
    - name: app_name
      description: "The name of the argo app to update"
    - name: app_revision
      default: "HEAD"
      description: "The revision of the argo app to update"
  steps:
    - name: deploy
      image: registry.cn-zhangjiakou.aliyuncs.com/marksugar/argocd:v2.7.2
      volumeMounts:
        - name: argocd-secret
          mountPath: /var/secret
      script: |
        #!/usr/bin/env sh      
        echo "starting argocd sync app"
        argocd login --insecure $(params.argocd_url) --username $(/bin/cat /var/secret/username) --password $(/bin/cat /var/secret/password)
        argocd app sync $(params.app_name) --revision $(params.app_revision)
        argocd app wait $(params.app_name) --health --timeout 120
      # if [ -z "$ARGOCD_AUTH_TOKEN" ]; then
      #   yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";
      # fi
      # argocd app sync "$(params.application-name)" --revision "$(params.revision)"
      # argocd app wait "$(params.application-name)" --health