resources:
- ../../base
# - path: healthcheck_patch.yaml
patches:
- path: patch.yaml
- path: pull-secret.yaml
- path: memorylimit_patch.yaml
namePrefix: production-

replicas:
- count: 4
  name: java-demo

namespace: linuxea-dev


commonLabels:
  app: linuxea

images:
- name: demo/linuxea
  newName: 172.16.100.46/test/java-demo
  newTag: v0.1-20230711-220052
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- files:
  - .dockerconfigjson=tmp/.docker/config.json
  name: harbor-auth
  type: kubernetes.io/dockerconfigjson
